// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AutocompleteController from "./autocomplete_controller";
application.register("autocomplete", AutocompleteController);

import MultiSelectController from "./multi_select_controller";
application.register("multi-select", MultiSelectController);

import TypeAheadSelectController from "./type_ahead_select_controller";
application.register("type-ahead-select", TypeAheadSelectController);
